name: fittracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.4.3
  firebase_core: ^3.6.0
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.8
  lints: ^4.0.0
  provider: ^6.1.2
  riverpod: ^2.5.1
  sliding_up_panel: ^2.0.0+1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  intl: ^0.18.0

flutter:
  uses-material-design: true
